### ISSUE TITLE
No longer working with Remine version 3.1.0?

### ISSUE THREAD

**Issue by batopilas** [giddie/redmine_default_assign#22]
The latest plugin version 0.4 no longer seems to work with the latest Redmine version 3.1.0.
When changing category and saving it, the default assignee for that category does no longer get assigned, the original setting just stays there.

Note: we first made an upgrade of our Redmine version and then upgraded the plugin (following the exact procedure on https://www.redmine.org/plugins/redmine_default_assign)

**Comment by giddie** [comment]
Since it's a new major release, it seems likely that the API has changed somewhat. I'll try to look into updating the plugin, but if it's urgent, do feel free to make any necessary fixes and make a pull request. It shouldn't be too complicated to fix, I imagine.

**Comment by batopilas** [comment]
Thank for looking into it. It is indeed rather urgent - it is really part of our daily operational business. But we have no knowledge of the internal redmine system nor of ruby. As a non profit organisation we currently have no means solving this issue. So if someone pick this up, we would be very grateful.

**Comment by batopilas** [comment]
I was actually surprised it was broken as someone on
https://www.redmine.org/plugins/redmine_default_assign
mentioned it works with 3.0.x

**Comment by giddie** [comment]
That's strange: I've upgraded a test Redmine to 3.1 and the plugin seems to be behaving OK for me. I created a category on a project with a default assignee, then edited the category, changing the default assignee. The change held OK when I saved. Do you see any error messages in your log when saving the category? Could you maybe explain the exact steps you go through to reproduce the issue?

**Comment by batopilas** [comment]
Thank you for your feedback. I've now done the same thing - created a new project etc. - and this is what I found: it works as long as the overall project doesn't have a default assignee assigned. But this is still different as before, because in our existing projects we have an overall project default assignee specified in the project information tab. This worked fine in the previous version but seems to be broken now. Could you confirm you experience the same? Thanks!

**Comment by giddie** [comment]
Ah, OK. I see the issue now. I'm going to see if there's an easy fix.

**Comment by batopilas** [comment]
Great, thanks!

**Comment by giddie** [comment]
OK, I think I've fixed the issue on master. Can you test it now?

**Comment by batopilas** [comment]
Unfortunately, no difference. Still not working. Same behaviour

**Comment by giddie** [comment]
Can you check that the plugin version is now 0.5 on your system?

**Comment by batopilas** [comment]
I doublechecked that. We have now version 0.5

**Comment by morfie78** [comment]
Hi! I have the same issue (I think).  I have Redmine 3.1.x.  The plugin installed fine, but when I set a default Assignee (either by Project-level or Global) in an existing project, then go to create an Issue, the drop down remains blank.
Any ideas?
Thanks!

**Comment by muradurm** [comment]
I confirm the plugin doesn't work with Redmine 3.2.1. Just the same as morfie78 described.

**Comment by giddie** [comment]
@morfie78 @muradurm What happens when you actually save the issue? Do you get the behaviour you want if you enable interactive mode in the plugin settings?

**Comment by mbullmann** [comment]
@giddie 

If I will migrate from Redmine 2.x to 4.x I can I have problem with running 4.x without this plugin? Regards

**Comment by giddie** [comment]
Sorry, I don't know. I haven't actively maintained a Redmine instance for about 7 years now. I'm happy to accept pull requests if it needs fixes, though. You could also check the Github network graph under "Insights" at the top to look for active forks. As far as I can tell, though, there are no forks that are significantly ahead of this one.

**Comment by thegcat** [comment]
@mbullmann Redmine can natively add default assignees to project since version 3.4, see https://www.redmine.org/issues/482#note-62. The migration in Redmine will take care to migrate existing default assignee data from this plugin. You can just remove the code from this plugin from your plugins directory (do _not_ run the down migrations for this plugin!) and update to Redmine 3.4 or higher and this functionality will be migrated to the built-in Redmine functionality.

@giddie you can probably close this issue. If you are interested I can contribute a PR to mark this plugin as requiring a Redmine version lower than 3.4 so that trying to start a Redmine with an updated version breaks loudly.

**Comment by giddie** [comment]
> Redmine can natively add default assignees to project since version 3.4, see https://www.redmine.org/issues/482#note-62. The migration in Redmine will take care to migrate existing default assignee data from this plugin.

This is great to hear :)

> If you are interested I can contribute a PR to mark this plugin as requiring a Redmine version lower than 3.4 so that trying to start a Redmine with an updated version breaks loudly.

Yes please; that would be awesome :+1:
